services:
  - type: web
    name: sua-api
    runtime: node
    buildCommand: |
      npm install
      npm install --only=dev  
      npm run build
      npm prune --production
    startCommand: npm start
