services:
  - type: web
    name: discount-api
    runtime: node
    branch: main
    buildCommand: npm run render-build
    startCommand: npm start
    env: node
    envVars:
      - key: NODE_ENV
      - key: PORT
      - key: MONGODB_URI
      - key: JWT_SECRET
