services:
  - type: web
    name: sua-api
    runtime: node
    buildCommand: |
      # Limpeza para garantir build limpo
      rm -rf node_modules dist package-lock.json

      # Instalação otimizada
      npm ci --no-audit

      # Build do projeto
      npm run build

      # Remove devDependencies após o build
      npm prune --production
    startCommand: node dist/server.js
